CREATE EVENT IF NOT EXISTS ev_WeeklySessionReminder
ON SCHEDULE EVERY 1 WEEK
STARTS TIMESTAMP(CURRENT_DATE + INTERVAL (7 - WEEKDAY(CURRENT_DATE)) DAY)  -- Next Sunday
DO
CALL SendWeeklySessionReminders();
